-- =====================================================
-- Add Summary Column to diio_transcripts
-- =====================================================
-- This adds a summary column to store meeting/call summaries
-- generated by AI (GPT-4o-mini)

-- Add summary column
ALTER TABLE diio_transcripts
ADD COLUMN IF NOT EXISTS summary TEXT;

-- Add index for summary searches (optional, for future full-text search)
CREATE INDEX IF NOT EXISTS idx_diio_transcripts_summary 
ON diio_transcripts USING GIN (to_tsvector('english', summary))
WHERE summary IS NOT NULL;

-- Add comment
COMMENT ON COLUMN diio_transcripts.summary IS 'AI-generated summary of the meeting/call transcript (generated by GPT-4o-mini)';

-- Verify column was added
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'diio_transcripts'
AND column_name = 'summary';
